#!/bin/sh

# this is quick way to find out what is 
# using space in programming flash 
# it shows the compiled object size

find ../harmony_badge_2017.X -name \*.o -exec ls -lt \{\} \; | sort -g -k 5,6
